# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo-sync" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "b24886407d4f99e602d80fb7c0978d3002742a44f106cff210ef10e094de1fdb"
      url "https://github.com/vectal-labs/repo-sync/releases/download/v#{version}/repo-sync_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f8a805a837d048503e90fc4bf29f0c3fe81bdabcb29b8c964420293c402c5fa8"
      url "https://github.com/vectal-labs/repo-sync/releases/download/v#{version}/repo-sync_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "repo-sync"
  desc "Keeps your Git repositories in sync automatically on macOS"
  homepage "https://github.com/vectal-labs/repo-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo-sync"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repo-sync"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `repo-sync setup` to choose repositories and install the background service.
  EOS
end
