# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo-sync" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "833c518c004a5ce509615c252eb0e2ed1ef6f3ade230c2d97235300fa02d9d6e"
      url "https://github.com/vectal-labs/repo-sync/releases/download/v#{version}/repo-sync_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3aa7557bfb671496049fa9bfdb25d4f54c7866100a26db9bcb17b10d36f8a282"
      url "https://github.com/vectal-labs/repo-sync/releases/download/v#{version}/repo-sync_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "repo-sync"
  desc "Keeps your Git repositories in sync automatically on macOS"
  homepage "https://github.com/vectal-labs/repo-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo-sync"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repo-sync"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `repo-sync setup` to choose repositories and install the background service.
  EOS
end
