# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoSync < Formula
  desc "Keeps your Git repositories in sync automatically on macOS"
  homepage "https://github.com/vectal-labs/repo-sync"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/vectal-labs/repo-sync/releases/download/v0.1.0/repo-sync_0.1.0_darwin_amd64.tar.gz"
    sha256 "c99a7485a2e19c89e450683c9265b17b42613fc6d55d47262dd704f67ab6cb60"

    define_method(:install) do
      bin.install "repo-sync"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/vectal-labs/repo-sync/releases/download/v0.1.0/repo-sync_0.1.0_darwin_arm64.tar.gz"
    sha256 "d73a2f53d3a8b17cb1731e5b39acc8f3cb9d0947617b9731e5a62b2cab6150bc"

    define_method(:install) do
      bin.install "repo-sync"
    end
  end

  def caveats
    <<~EOS
      Run `repo-sync setup` to choose repositories and install the background service.
    EOS
  end
end
